name: Frontend CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CI: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Upload build folder to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "build"
          target: "/home/ubuntu/temp_build"
          # target: "/usr/share/nginx/html" # 권한 없음

          # 권한 모두 허락하는 대신 sudo 명령어 actions에서 처리
      - name: Move build to nginx with sudo
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -rf /usr/share/nginx/html/*
            sudo mv /home/ubuntu/temp_build/build/* /usr/share/nginx/html/
            sudo rm -rf /home/ubuntu/temp_build
